language: php
sudo: required
dist: xenial

cache:
    directories:
    - $HOME/.composer/cache

matrix:
    include:
    - php: 8.3
    fast_finish: true

before_script:
- wget http://packages.couchbase.com/releases/couchbase-release/couchbase-release-1.0-4-amd64.deb
- sudo dpkg -i couchbase-release-1.0-4-amd64.deb
- sudo apt-get update
- sudo apt-get install libcouchbase-dev build-essential php-pear php8.3-dev zlib1g-dev
- sudo pecl install couchbase
- echo "extension=couchbase.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
- composer install

script:
- mkdir -p tests/coverage
- vendor/bin/phpunit

after_script:
- php vendor/bin/php-coveralls -v

before_install:
- echo "memory_limit=2048M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini