language: php
sudo: required

cache:
    directories:
    - $HOME/.composer/cache

matrix:
    include:
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    fast_finish: true

before_script:
- wget http://packages.couchbase.com/releases/couchbase-release/couchbase-release-1.0-4-amd64.deb
- sudo dpkg -i couchbase-release-1.0-4-amd64.deb
- sudo apt-get update
- sudo apt-get install libcouchbase-dev build-essential php-dev zlib1g-dev
- sudo pecl install couchbase
- echo "extension=couchbase.so" >> /etc/php/7.0/apache2/php.ini
- composer install

script:
- mkdir -p tests/coverage
- vendor/bin/phpunit

after_script:
- php vendor/bin/coveralls -v

before_install:
- echo "memory_limit=2048M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini